export const diseases = [
  'Diabetes', 'Hypertension', 'Asthma', 'Heart Disease',
  'Thyroid Disorders', 'Arthritis', 'COPD', 'Kidney Disease',
  'Liver Disease', 'Cancer', 'Epilepsy', 'Depression',
  'Anxiety', 'Migraine', 'Anemia', 'None'
];

export const mockPatients = [
  {
    id: 1,
    name: 'Rahul Sharma',
    age: 34,
    gender: 'Male',
    phone: '+91 98765 43210',
    email: 'rahul.sharma@email.com',
    address: '45 MG Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    diseases: ['Diabetes', 'Hypertension'],
    allergies: 'Penicillin',
    medications: 'Metformin 500mg, Amlodipine 5mg',
    surgeries: 'Appendectomy (2018)',
    familyHistory: 'Father - Diabetes, Mother - Hypertension',
    reports: ['blood_test_jan2026.pdf', 'ecg_report.pdf'],
    symptoms: 'Persistent headache, blurred vision, occasional dizziness',
    duration: '2 weeks',
    severity: 'Medium',
    notes: 'Symptoms worsen in the evening. Blood sugar levels fluctuating.',
    status: 'waiting',
    consultationTime: null,
  },
  {
    id: 2,
    name: 'Priya Patel',
    age: 28,
    gender: 'Female',
    phone: '+91 87654 32109',
    email: 'priya.patel@email.com',
    address: '12 Jubilee Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    diseases: ['Asthma'],
    allergies: 'Dust, Pollen',
    medications: 'Salbutamol Inhaler',
    surgeries: 'None',
    familyHistory: 'Mother - Asthma',
    reports: ['chest_xray.pdf'],
    symptoms: 'Wheezing, shortness of breath, chest tightness after exertion',
    duration: '5 days',
    severity: 'High',
    notes: 'Recent change in weather triggered symptoms. Using inhaler 3-4 times daily.',
    status: 'in-consultation',
    consultationTime: '10:30 AM',
  },
  {
    id: 3,
    name: 'Amit Kumar',
    age: 45,
    gender: 'Male',
    phone: '+91 76543 21098',
    email: 'amit.kumar@email.com',
    address: '78 Connaught Place',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    diseases: ['Heart Disease', 'Hypertension'],
    allergies: 'None',
    medications: 'Atorvastatin 20mg, Aspirin 75mg',
    surgeries: 'Angioplasty (2022)',
    familyHistory: 'Father - Heart Attack, Brother - Hypertension',
    reports: ['angiography_2022.pdf', 'lipid_profile.pdf', 'echo_report.pdf'],
    symptoms: 'Mild chest discomfort, fatigue, swelling in ankles',
    duration: '1 week',
    severity: 'High',
    notes: 'Recently missed medications for 3 days. BP readings: 150/95.',
    status: 'completed',
    consultationTime: '09:00 AM',
  },
  {
    id: 4,
    name: 'Sneha Reddy',
    age: 22,
    gender: 'Female',
    phone: '+91 65432 10987',
    email: 'sneha.reddy@email.com',
    address: '23 Brigade Road',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    diseases: ['None'],
    allergies: 'Sulfa drugs',
    medications: 'None',
    surgeries: 'None',
    familyHistory: 'No significant history',
    reports: [],
    symptoms: 'Persistent cough, low-grade fever, body ache',
    duration: '3 days',
    severity: 'Low',
    notes: 'Started after getting wet in rain. No travel history.',
    status: 'waiting',
    consultationTime: null,
  },
  {
    id: 5,
    name: 'Vikram Singh',
    age: 52,
    gender: 'Male',
    phone: '+91 54321 09876',
    email: 'vikram.singh@email.com',
    address: '56 Civil Lines',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    diseases: ['Diabetes', 'Thyroid Disorders'],
    allergies: 'Ibuprofen',
    medications: 'Insulin, Levothyroxine 50mcg',
    surgeries: 'Knee replacement (2020)',
    familyHistory: 'Mother - Diabetes, Sister - Thyroid',
    reports: ['hba1c_report.pdf', 'thyroid_profile.pdf'],
    symptoms: 'Numbness in feet, increased thirst, frequent urination',
    duration: '10 days',
    severity: 'Medium',
    notes: 'HbA1c was 8.2 last month. Neuropathy symptoms increasing.',
    status: 'waiting',
    consultationTime: null,
  },
];

export const mockPrescriptions = [
  {
    id: 1,
    patientId: 3,
    patientName: 'Amit Kumar',
    date: '2026-04-08',
    diagnosis: 'Unstable Angina with Uncontrolled Hypertension',
    medicines: [
      { name: 'Atorvastatin', dosage: '40mg', duration: '30 days', instructions: 'Once daily at bedtime' },
      { name: 'Clopidogrel', dosage: '75mg', duration: '30 days', instructions: 'Once daily after breakfast' },
      { name: 'Ramipril', dosage: '5mg', duration: '30 days', instructions: 'Once daily in morning' },
    ],
    notes: 'Strict salt restriction. Monitor BP twice daily. Follow up in 2 weeks. Avoid heavy physical exertion.',
    doctorName: 'Dr. Ananya Mehta',
  },
  {
    id: 2,
    patientId: 2,
    patientName: 'Priya Patel',
    date: '2026-04-09',
    diagnosis: 'Acute Exacerbation of Bronchial Asthma',
    medicines: [
      { name: 'Montelukast', dosage: '10mg', duration: '14 days', instructions: 'Once daily at night' },
      { name: 'Budesonide Inhaler', dosage: '200mcg', duration: '30 days', instructions: 'Twice daily' },
      { name: 'Cetirizine', dosage: '10mg', duration: '7 days', instructions: 'Once daily at night' },
    ],
    notes: 'Avoid dust and pollen exposure. Use mask outdoors. Review inhaler technique. Follow up in 1 week.',
    doctorName: 'Dr. Ananya Mehta',
  },
];
